language: java
jdk:
  - oraclejdk8

env:
  global:
    - SONATYPE_USERNAME=culturegraph
    - secure: "qDjYOxrFklEkJIGBGYgexka5diGplkfVWTca9GwjjgQwYOj5hDsjGU71tgCJOxmOxneyWVj+i+TBospWgBUnKE8MGkKlO2dmyRLwIaK6dptQtMs8R0mQWu2rst4aiaz+VOXN/oiC7PqcW/ZDv33vR8JQPfGlt3SzYVlf4OZm2WsFlp9WAwAj69ubpXBSZaCrJKRsPC5Qqcc87+w4nJ9D57kblDMo0Pe8zvqEhijRKp7qcUKqxAnLkV4blIZJ+r3G7FMM0EBhwuQj/imKts0yK4PGKuDpe3AL5AmLS30yzpJqZd9eV3XeFcX9x0RS3bqQ0aXP7e9E1Uqmr41r49UVvVm/OEsSmJ3raLdZyD1gGHuZ/onjg+dFkyCs7piLueZluJwS/ZDomPJnmQaMCOeV5x+Fv+5vWzASATyyco9RSxr53aOVM7hr1qVK8m1r9e+KDKxOC0RWARvQG/CW+tzEheJJPNnssvDSaH0640dTVoBdqLoozrPW5jarbpcAKcsLynM6Hu+rnvoE3Lri7ZoYkbi1YY9dU268zRn/FMVm1tYajKi3DydiAeVQF4FBmiJtxtt1Zxwdc7trhWIzZhBZZ1rBvFDPBgTEh66S0kcJFyU223GsCGLrY+LWbWqp4gxKW52CKZu9YT2RsDztUvhBBPs/pmIQ7tCyOtmuMTQ5xYk="

after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && { python travis-ci/configure-mvn.py ; mvn clean deploy --settings ~/.m2/mySettings.xml -Dgpg.skip=true -Psonatype-oss-release ; }"

